# Generated by Django 2.2.9 on 2021-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210328_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ManyToManyField(blank=True, to='posts.Group'),
        ),
    ]
